name: storage_user_repository
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18
  search_user_repository:
    path: ../../packages/search_user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^2.0.1

